version: '3.8'
services:
  app:
    build: .
    container_name: gotripes-app
    ports:
      - "8081:8080"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - PORT=8080
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=http://localhost:8081
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
